on:
  push:
    branches:
      - main
    paths:
      - .github/actions/**

jobs:
  update-deployments-dependences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get token from github app
        id: github-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ vars.GH_APPLICATION_ID }}
          private_key: ${{ secrets.GH_APPLICATION_KEY }}
          
      - name: Trigger deployment workflow
        run: |
          curl -LvfS \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.LEWISM20_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/matt-lewis-testing-org/approve-and-merge/actions/workflows/update-actions.yml/dispatches \
            -d '{"ref": "main", "inputs":{"gh_token":"${{ steps.github-app.outputs.token }}"}}'
