on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/actions/*

jobs:
  update-deployments-dependences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
          
      - name: Trigger deployment workflow
        run: |
          curl -LvfS \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.LEWISM20_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/matt-lewis-testing-org/deployments/approve-and-merge/workflows/update-actions.yml/dispatches \
            -d '{"ref": "main", "inputs":{"gh_token":"${{ secrets.LEWISM20_GH_TOKEN }}"}}'
